package ca.gc.aafc.seqdb.api.dtoMappers;

import org.mapstruct.InheritInverseConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

import ca.gc.aafc.seqdb.api.dto.GroupDto;
import ca.gc.aafc.seqdb.entities.Group;

@Mapper(componentModel = "spring")
public interface GroupMapper {

  // This instance reference will refer to a GroupMapperImplementation generated by MapStruct which
  // has all the mapping logic.
  GroupMapper INSTANCE = Mappers.getMapper(GroupMapper.class);

  // Mapstruct will look at fields that are common between the Return Type (GroupDto) and the
  // Argument(Group) to impliment custom mapping you will need to define them @see
  // http://mapstruct.org/documentation/stable/reference/html/#adding-custom-methods

  GroupDto entityToDto(Group group);

  @InheritInverseConfiguration
  Group dtoToEntity(GroupDto groupDto);

}
